

material: SKULL_ITEM

#You can find a head value from minecraft-heads.com
skullOwnerIfMaterialSkull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNhYWE5OTMyM2I0OWFkOTIyYTM4Y2JiNTg2YzgxYjM4MTYwZTFhZWFiYzY3NTcyMGZkOGVmZDg3YTY3ZmM1NCJ9fX0="





#Don't change this option on play season
name: "&cShulker Box"

#If shulker block damaged by a damage will drop
canDamage: false


visibleItemsInLore: true


makeParticle: true
shulkerOpenParticle: HEART

makeSound: true
shulkerOpenSound: CHEST_OPEN
shulkerCloseSound: CHEST_CLOSE




msgPerm: "&cYou don't have permission for this command"
msgGived: "&aYou give a shulker box a player"
msgTargetNull: "&cYour target player was null"
msgConfigReloaded: "&aConfiguration successfully reloaded"
msgAvailable: "&aAvailable options are [reload], [give <target>]"